export enum EventType {
  BOT_CONNECTED = 'BOT_CONNECTED',
  BOT_DISCONNECTED = 'BOT_DISCONNECTED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_DELETED = 'MESSAGE_DELETED',
  WARNING_ISSUED = 'WARNING_ISSUED',
  STRIKE_ADDED = 'STRIKE_ADDED',
  USER_MUTED = 'USER_MUTED',
  USER_KICKED = 'USER_KICKED',
  COMMAND_EXECUTED = 'COMMAND_EXECUTED',
  PLUGIN_TOGGLED = 'PLUGIN_TOGGLED',
  TASK_EXECUTED = 'TASK_EXECUTED',
}

export interface BotEvent {
  type: EventType;
  payload: any;
  timestamp: Date;
}
